import { ReactNode } from 'react'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Header from '@/components/molecule/Layout/Header'
import Footer from '@/components/molecule/Layout/Footer'


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: ReactNode
}) {
  return (
    <html lang="fa">
        <body style={{margin:0,padding:0}}>
        <header>
          <Header>{children}</Header>
        </header>
        {children}
        <footer>
          <Footer />
        </footer>
        </body>
    </html>
  );
}