import { ReactNode } from 'react'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Header from '@/components/atom/layout/Header'
import Footer from '@/components/atom/layout/Footer'

type Props = {
  children: ReactNode;
};


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: Props) { 
  return (
    <html lang="en">
      <header>
        <Header>{children}</Header>
      </header>
      <body className={inter.className}>{children}</body>
      <footer>
        <Footer />
      </footer>
    </html>
  );
}
